name: drive
summary: Google Drive client for the commandline
version: current
description:
  drive is a tiny program to pull or push Google Drive files.
confinement: strict
grade: stable

apps:
  drive:
    command: bin/drive
    plugs: [home, network, network-bind]

parts:
  drive:
    plugin: go
    source: https://github.com/odeke-em/drive
    source-type: git
    go-importpath: github.com/odeke-em/drive
    build-packages: [gcc, libgudev-1.0-dev]
